FROM nginx:alpine

#WORKDIR /app


COPY index.html /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chmod 777 /usr/share/nginx/html/index.html
RUN chmod 777 /etc/nginx/conf.d/default.conf


HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost/


CMD ["nginx", "-g", "daemon off;"]
